
stages:
  - release

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never

build_docker:
  cache: { }
  stage: release
  interruptible: true
  tags:
    - saas-linux-large-amd64 # need more diskspace for this build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --custom-platform=linux/arm64 --custom-platform=linux/amd64 --build-arg "BINGO=false" --build-arg "COMMIT_SHA=${CI_COMMIT_SHA}" --build-arg "BUILD_BRANCH=main"
